package test

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulation extends Simulation {

	val httpProtocol = http
		.baseURL("http://detectportal.firefox.com")
		.inferHtmlResources()
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0")

	val headers_0 = Map("Pragma" -> "no-cache")

    val uri1 = "http://detectportal.firefox.com/success.txt"

	val scn = scenario("RecordedSimulation")
		.exec(http("request_0")
			.get("/success.txt")
			.headers(headers_0))
		.pause(11)
		.exec(http("request_1")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_2")
			.get("/success.txt")
			.headers(headers_0),
            http("request_3")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(7)
		.exec(http("request_4")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_5")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(1)
		.exec(http("request_6")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_7")
			.get("/success.txt")
			.headers(headers_0),
            http("request_8")
			.get("/success.txt")
			.headers(headers_0),
            http("request_9")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(10)
		.exec(http("request_10")
			.get("/success.txt")
			.headers(headers_0))
		.pause(12)
		.exec(http("request_11")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_12")
			.get("/success.txt")
			.headers(headers_0),
            http("request_13")
			.get("/success.txt")
			.headers(headers_0),
            http("request_14")
			.get("/success.txt")
			.headers(headers_0),
            http("request_15")
			.get("/success.txt")
			.headers(headers_0),
            http("request_16")
			.get("/success.txt")
			.headers(headers_0),
            http("request_17")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(1)
		.exec(http("request_18")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_19")
			.get("/success.txt")
			.headers(headers_0),
            http("request_20")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(2)
		.exec(http("request_21")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_22")
			.get("/success.txt")
			.headers(headers_0),
            http("request_23")
			.get("/success.txt")
			.headers(headers_0),
            http("request_24")
			.get("/success.txt")
			.headers(headers_0),
            http("request_25")
			.get("/success.txt")
			.headers(headers_0),
            http("request_26")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(1)
		.exec(http("request_27")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_28")
			.get("/success.txt")
			.headers(headers_0),
            http("request_29")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(1)
		.exec(http("request_30")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_31")
			.get("/success.txt")
			.headers(headers_0),
            http("request_32")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(1)
		.exec(http("request_33")
			.get("/success.txt")
			.headers(headers_0))
		.pause(4)
		// getData
		.exec(http("request_34")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_35")
			.get("/success.txt")
			.headers(headers_0),
            http("request_36")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(6)
		.exec(http("request_37")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_38")
			.get("/success.txt")
			.headers(headers_0),
            http("request_39")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(9)
		.exec(http("request_40")
			.get("/success.txt")
			.headers(headers_0))
		.pause(5)
		.exec(http("request_41")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_42")
			.get("/success.txt")
			.headers(headers_0),
            http("request_43")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(7)
		.exec(http("request_44")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_45")
			.get("/success.txt")
			.headers(headers_0),
            http("request_46")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(37)
		.exec(http("request_47")
			.get("/success.txt")
			.headers(headers_0)
			.resources(http("request_48")
			.get("/success.txt")
			.headers(headers_0),
            http("request_49")
			.get("/success.txt")
			.headers(headers_0)))
		.pause(12)
		.exec(http("request_50")
			.get("/success.txt")
			.headers(headers_0))
		.pause(3)
		.exec(http("request_51")
			.get("/success.txt")
			.headers(headers_0))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}